Parameters:
  AppName:
    Type: String
    Default: claimo

  # Fetched from SSM at deploy time
  CodeArtifactDomainOwner:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /claimo/account-id

Resources:
  FrontendCICD:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cicd/frontend.cicd.yaml
      Parameters:
        AppName: !Ref AppName
        CodeArtifactDomainOwner: !Ref CodeArtifactDomainOwner

  BackendCICD:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cicd/backend.cicd.yaml
      Parameters:
        AppName: !Ref AppName
        CodeArtifactDomainOwner: !Ref CodeArtifactDomainOwner
