/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterSsoCallbackRouteImport } from './routes/register/sso-callback'
import { Route as LoginSsoCallbackRouteImport } from './routes/login/sso-callback'
import { Route as NavbarPricingRouteImport } from './routes/_navbar/pricing'
import { Route as NavbarFeaturesRouteImport } from './routes/_navbar/features'
import { Route as NavbarDocsRouteImport } from './routes/_navbar/docs'
import { Route as NavbarBimViewerRouteImport } from './routes/_navbar/bim-viewer'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedViewerProjectIdModelIdRouteImport } from './routes/_authenticated/viewer/$projectId/$modelId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSsoCallbackRoute = RegisterSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => RegisterRoute,
} as any)
const LoginSsoCallbackRoute = LoginSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => LoginRoute,
} as any)
const NavbarPricingRoute = NavbarPricingRouteImport.update({
  id: '/_navbar/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarFeaturesRoute = NavbarFeaturesRouteImport.update({
  id: '/_navbar/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarDocsRoute = NavbarDocsRouteImport.update({
  id: '/_navbar/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarBimViewerRoute = NavbarBimViewerRouteImport.update({
  id: '/_navbar/bim-viewer',
  path: '/bim-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedViewerProjectIdModelIdRoute =
  AuthenticatedViewerProjectIdModelIdRouteImport.update({
    id: '/viewer/$projectId/$modelId',
    path: '/viewer/$projectId/$modelId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/bim-viewer': typeof NavbarBimViewerRoute
  '/docs': typeof NavbarDocsRoute
  '/features': typeof NavbarFeaturesRoute
  '/pricing': typeof NavbarPricingRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/register/sso-callback': typeof RegisterSsoCallbackRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/viewer/$projectId/$modelId': typeof AuthenticatedViewerProjectIdModelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/bim-viewer': typeof NavbarBimViewerRoute
  '/docs': typeof NavbarDocsRoute
  '/features': typeof NavbarFeaturesRoute
  '/pricing': typeof NavbarPricingRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/register/sso-callback': typeof RegisterSsoCallbackRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/viewer/$projectId/$modelId': typeof AuthenticatedViewerProjectIdModelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_navbar/bim-viewer': typeof NavbarBimViewerRoute
  '/_navbar/docs': typeof NavbarDocsRoute
  '/_navbar/features': typeof NavbarFeaturesRoute
  '/_navbar/pricing': typeof NavbarPricingRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/register/sso-callback': typeof RegisterSsoCallbackRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/viewer/$projectId/$modelId': typeof AuthenticatedViewerProjectIdModelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/settings'
    | '/bim-viewer'
    | '/docs'
    | '/features'
    | '/pricing'
    | '/login/sso-callback'
    | '/register/sso-callback'
    | '/projects/$projectId'
    | '/projects/'
    | '/viewer/$projectId/$modelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/settings'
    | '/bim-viewer'
    | '/docs'
    | '/features'
    | '/pricing'
    | '/login/sso-callback'
    | '/register/sso-callback'
    | '/projects/$projectId'
    | '/projects'
    | '/viewer/$projectId/$modelId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_navbar/bim-viewer'
    | '/_navbar/docs'
    | '/_navbar/features'
    | '/_navbar/pricing'
    | '/login/sso-callback'
    | '/register/sso-callback'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/'
    | '/_authenticated/viewer/$projectId/$modelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  RegisterRoute: typeof RegisterRouteWithChildren
  NavbarBimViewerRoute: typeof NavbarBimViewerRoute
  NavbarDocsRoute: typeof NavbarDocsRoute
  NavbarFeaturesRoute: typeof NavbarFeaturesRoute
  NavbarPricingRoute: typeof NavbarPricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/sso-callback': {
      id: '/register/sso-callback'
      path: '/sso-callback'
      fullPath: '/register/sso-callback'
      preLoaderRoute: typeof RegisterSsoCallbackRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/login/sso-callback': {
      id: '/login/sso-callback'
      path: '/sso-callback'
      fullPath: '/login/sso-callback'
      preLoaderRoute: typeof LoginSsoCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_navbar/pricing': {
      id: '/_navbar/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof NavbarPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbar/features': {
      id: '/_navbar/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof NavbarFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbar/docs': {
      id: '/_navbar/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof NavbarDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbar/bim-viewer': {
      id: '/_navbar/bim-viewer'
      path: '/bim-viewer'
      fullPath: '/bim-viewer'
      preLoaderRoute: typeof NavbarBimViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/viewer/$projectId/$modelId': {
      id: '/_authenticated/viewer/$projectId/$modelId'
      path: '/viewer/$projectId/$modelId'
      fullPath: '/viewer/$projectId/$modelId'
      preLoaderRoute: typeof AuthenticatedViewerProjectIdModelIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedViewerProjectIdModelIdRoute: typeof AuthenticatedViewerProjectIdModelIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedViewerProjectIdModelIdRoute:
    AuthenticatedViewerProjectIdModelIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginSsoCallbackRoute: typeof LoginSsoCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSsoCallbackRoute: LoginSsoCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface RegisterRouteChildren {
  RegisterSsoCallbackRoute: typeof RegisterSsoCallbackRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterSsoCallbackRoute: RegisterSsoCallbackRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  RegisterRoute: RegisterRouteWithChildren,
  NavbarBimViewerRoute: NavbarBimViewerRoute,
  NavbarDocsRoute: NavbarDocsRoute,
  NavbarFeaturesRoute: NavbarFeaturesRoute,
  NavbarPricingRoute: NavbarPricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
