clerk.secret-key=${CLERK_SECRET_KEY}
clerk.invitation-redirect-url=${CLERK_INVITATION_REDIRECT_URL}
clerk.user-created-webhook-secret=${CLERK_USER_CREATED_WEBHOOK_SECRET}
clerk.user-deleted-webhook-secret=${CLERK_USER_DELETED_WEBHOOK_SECRET}
clerk.invitation-created-webhook-secret=${CLERK_INVITATION_CREATED_WEBHOOK_SECRET}
clerk.invitation-accepted-webhook-secret=${CLERK_INVITATION_ACCEPTED_WEBHOOK_SECRET}
clerk.invitation-revoked-webhook-secret=${CLERK_INVITATION_REVOKED_WEBHOOK_SECRET}

# ==========================================
# DATABASE
# ==========================================
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=false
spring.flyway.clean-before-migrate=true
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2


spring.servlet.multipart.max-file-size=3MB
# ==========================================
# RATE LIMITING
# ==========================================
app.ratelimit.requests-per-minute=60

# ==========================================
# SECURITY
# ==========================================
app.security.issuer-uri=${CLERK_ISSUER_URI}
app.security.allowed-origins=${ALLOWED_ORIGINS}


# ==========================================
# AZURE BLOB STORAGE
# ==========================================
spring.cloud.azure.storage.blob.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
spring.cloud.azure.storage.blob.container-name=${AZURE_STORAGE_CONTAINER_NAME}



# ==========================================
# LOGGING
# ==========================================
debug=false
logging.level.root=INFO
logging.level.com.admina.api=INFO
logging.level.com.zaxxer.hikari=INFO
logging.level.org.apache.tomcat=WARN
logging.level.org.apache.coyote=WARN
logging.level.org.springframework.web.servlet=WARN
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF

logging.level.com.claimo.api.config.DataSourceProxyConfig=DEBUG
