spring.application.name=api
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${ACTIVE_PROFILE}
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info

# ==========================================
# RATE LIMITING
# ==========================================
app.ratelimit.window-seconds=60
app.ratelimit.exclude-paths=/actuator/info,/actuator/health,/swagger-ui.html,/v3/api-docs/**,/api/v1/subscriptions/**,/api/v1/webhooks/stripe

# ==========================================
# SECURITY
# ==========================================
app.security.public-endpoints=/actuator/info,/actuator/health,/swagger-ui.html,/swagger-ui/**,/v3/api-docs,/api/v1/webhooks/stripe,/api/v1/webhooks/**
