spring.application.name=api
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${ACTIVE_PROFILE}

# ==========================================
# SECURITY
# ==========================================
app.ratelimit.enabled=true
app.ratelimit.window-seconds=60
app.ratelimit.exclude-paths=/actuator/info,/actuator/health,/swagger-ui.html,/v3/api-docs/**,/api/v1/subscriptions/**,/api/v1/webhooks/stripe